/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mygame;

import com.jme3.system.AppSettings;
import java.awt.Dimension;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.ToolTipManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.codehaus.groovy.control.CompilationFailedException;



/**
 *
 * @author Amir72c(Amirooo)
 */
public class Map_making extends javax.swing.JFrame {

    /**
     * Creates new form Map_making
     */
    Main_menu my_parent;
    
    public Map_making(Main_menu parent) {
        
        my_parent=parent;
        initComponents();
        my_init();
    }
    
    String background_list[];
    String Texture_list[];
    Map_constructor constructing_map;

    public void my_init()
    {
        jPopupMenu1.addFocusListener(new FocusListener() {

            public void focusGained(FocusEvent e) {
                
            }

            public void focusLost(FocusEvent e) {
                jPopupMenu1.setVisible(false);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jDialog3 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDialog4 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        new_map_button = new javax.swing.JMenuItem();
        Test_button = new javax.swing.JMenuItem();
        Save_button = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Exit_button = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mario_spawn = new javax.swing.JMenuItem();
        add_floor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel1.setText("Width:");

        jLabel2.setText("Height:");

        jLabel3.setText("Background:");

        jTextField1.setText("1000");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("1000");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "background8.jpg" }));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel4.setText("Start point x:");

        jLabel5.setText("Start point y:");

        jLabel6.setText("Width:");

        jLabel7.setText("Height:");

        jLabel8.setText("Texture:");

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.setText("100");

        jTextField4.setText("100");

        jTextField5.setText("200");

        jTextField6.setText("200");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Textures/archibrick01.jpg" }));

        jLabel9.setText("Tile_x:");

        jLabel10.setText("Tile_y:");

        jTextField7.setText("1");

        jTextField8.setText("1");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel11.setText("X location:");

        jLabel12.setText("Y location:");

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jMenuItem4.setText("Add floor/wall");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setText("Set Mario location");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem3.setText("Add enemy");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jLabel13.setText("X location:");

        jLabel14.setText("Y location:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monster", "enemy 2", "enemy 3" }));

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField12)))
                .addContainerGap())
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        new_map_button.setText("New");
        new_map_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_map_buttonActionPerformed(evt);
            }
        });
        jMenu1.add(new_map_button);

        Test_button.setText("Test");
        Test_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test_buttonActionPerformed(evt);
            }
        });
        jMenu1.add(Test_button);

        Save_button.setText("Save");
        Save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_buttonActionPerformed(evt);
            }
        });
        jMenu1.add(Save_button);

        jMenuItem1.setText("Load");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Exit_button.setText("Exit");
        jMenu1.add(Exit_button);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mario_spawn.setText("Mario spawn location");
        mario_spawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mario_spawnActionPerformed(evt);
            }
        });
        jMenu2.add(mario_spawn);

        add_floor.setText("Add floor/wall");
        add_floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_floorActionPerformed(evt);
            }
        });
        jMenu2.add(add_floor);

        jMenuItem2.setText("Add enemy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_map_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_map_buttonActionPerformed
        // TODO add your handling code here:
        jDialog1.setBounds(0, 0, 240, 220);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_new_map_buttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void add_floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_floorActionPerformed
        // TODO add your handling code here:
        if(constructing_map!=null)
        {
            jDialog2.setBounds(0, 0, 290, 390);
            jDialog2.setVisible(true);
        }
        
    }//GEN-LAST:event_add_floorActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(isInteger(jTextField1.getText()) && isInteger(jTextField2.getText()))
        {
            constructing_map=new Map_constructor(this,Integer.parseInt(jTextField1.getText()),Integer.parseInt(jTextField2.getText()),jComboBox1.getSelectedItem().toString());
            jPanel1.add(constructing_map);
            
            jPanel1.setPreferredSize(new Dimension(Integer.parseInt(jTextField1.getText()),Integer.parseInt(jTextField2.getText())));
            this.repaint();
            this.revalidate();
            jDialog1.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    boolean iseditting=false;
    int editting_order=0;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(isInteger(jTextField3.getText()) && isInteger(jTextField4.getText()) && isInteger(jTextField5.getText()) && isInteger(jTextField6.getText()) && isFloat(jTextField7.getText()) && isFloat(jTextField8.getText()))
        {
            if(iseditting==false)
            {
                constructing_map.floors[constructing_map.num_floor]=new constructing_floor(constructing_map,constructing_map.num_floor,Integer.parseInt(jTextField3.getText()),Integer.parseInt(jTextField4.getText()),Integer.parseInt(jTextField5.getText()),Integer.parseInt(jTextField6.getText()),jComboBox2.getSelectedItem().toString(),Float.parseFloat(jTextField7.getText()),Float.parseFloat(jTextField8.getText()));
                constructing_map.floors[constructing_map.num_floor].setVisible(true);
                constructing_map.add(constructing_map.floors[constructing_map.num_floor]);
                constructing_map.num_floor=constructing_map.num_floor+1;
                constructing_map.repaint();
                jDialog2.dispose();
            }else{
                constructing_map.floors[editting_order].my_start_x=Integer.parseInt(jTextField3.getText());
                constructing_map.floors[editting_order].my_start_y=Integer.parseInt(jTextField4.getText());
                constructing_map.floors[editting_order].my_width=Integer.parseInt(jTextField5.getText());
                constructing_map.floors[editting_order].my_height=Integer.parseInt(jTextField6.getText());
                constructing_map.floors[editting_order].my_texture=jComboBox2.getSelectedItem().toString();
                constructing_map.floors[editting_order].my_tile_x=Float.parseFloat(jTextField7.getText());
                constructing_map.floors[editting_order].my_tile_y=Float.parseFloat(jTextField8.getText());
                constructing_map.floors[editting_order].setBounds(Integer.parseInt(jTextField3.getText()), constructing_map.my_height-Integer.parseInt(jTextField4.getText())-Integer.parseInt(jTextField6.getText()), Integer.parseInt(jTextField5.getText()), Integer.parseInt(jTextField6.getText()));
                constructing_map.floors[editting_order].setText(jComboBox2.getSelectedItem().toString());
                constructing_map.repaint();
                jDialog2.dispose();
                iseditting=false;
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Test_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test_buttonActionPerformed
        // TODO add your handling code here:
        Main_renderer app = new Main_renderer(my_parent,"");
        app.isspec=true;
        app.test_map=constructing_map;
        app.setShowSettings(false);
        AppSettings settings = new AppSettings(true);
        settings.setResolution(800, 600);
        settings.setBitsPerPixel(24);
        settings.setFrameRate(50);
        app.setSettings(settings);
        app.setPauseOnLostFocus(false);
        app.start();
        //this.setVisible(false);
    }//GEN-LAST:event_Test_buttonActionPerformed

    private void mario_spawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mario_spawnActionPerformed
        // TODO add your handling code here:
        if(constructing_map!=null && constructing_map.mario_location==null)
        {
            jDialog3.setBounds(0, 0, 190, 180);
            jDialog3.setVisible(true);
        }
    }//GEN-LAST:event_mario_spawnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(isInteger(jTextField9.getText()) && isInteger(jTextField10.getText()))
        {
            if(iseditting==false)
            {
                constructing_map.mario_location=new spawn_location(constructing_map,Integer.parseInt(jTextField9.getText()),Integer.parseInt(jTextField10.getText()),"Mario");
                constructing_map.mario_location.setVisible(true);
                constructing_map.add(constructing_map.mario_location);
                //constructing_map.num_floor=constructing_map.num_floor+1;
                constructing_map.repaint();
                jDialog3.dispose();
            }else{
                constructing_map.mario_location.my_x_location=Integer.parseInt(jTextField9.getText());
                constructing_map.mario_location.my_y_location=Integer.parseInt(jTextField10.getText());
                constructing_map.mario_location.setBounds(Integer.parseInt(jTextField9.getText()),constructing_map.my_height-Integer.parseInt(jTextField10.getText())-constructing_map.mario_location.my_height,constructing_map.mario_location.my_width,constructing_map.mario_location.my_height);
                constructing_map.repaint();
                jDialog3.dispose();
                iseditting=false;
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc_save=new JFileChooser();
        fc_save.setFileFilter(new FileNameExtensionFilter("NC file", "nc"));
        fc_save.setAcceptAllFileFilterUsed(false);
        int returnVal = fc_save.showSaveDialog(this);
        String[] save_exts = ((FileNameExtensionFilter)fc_save.getFileFilter()).getExtensions();
        String save_final_exts = save_exts[0];
        if (returnVal == JFileChooser.APPROVE_OPTION){
                String file_name = fc_save.getSelectedFile().getName();
                String save_file_path = fc_save.getSelectedFile().getAbsolutePath();
                try {
                    prepare_data();
                    write_data(save_file_path,file_name,save_final_exts);
                } catch (IOException ex) {
                    
                }
        }
    }//GEN-LAST:event_Save_buttonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc_save=new JFileChooser();
        fc_save.setFileFilter(new FileNameExtensionFilter("NC file", "nc"));
        fc_save.setAcceptAllFileFilterUsed(false);
        int returnVal = fc_save.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION){
                String file_name = fc_save.getSelectedFile().getName();
                String load_file_path = fc_save.getSelectedFile().getAbsolutePath();
                my_parent.load_for_play=false;
                try {
                my_parent.main_shell.evaluate(new File(load_file_path));
                //map_array[0][0]='A';
                //System.out.println((char)map_array[0][0]);
                //floor[0]=new Floor(this,new Point(0,0),1000,50,"Textures/archibrick01.jpg",0f,0f);
                //floor[1]=new Floor(this,new Point(0,60),20,500,"Textures/archibrick01.jpg",0f,0f);
                //floor[3]=new Floor(this,new Point(400,60),40,500,"Textures/archibrick01.jpg",0f,0f);
                //floor[3]=new Floor(this,new Point(400,60),40,500,"Textures/archibrick01.jpg",0f,0f);
                } catch (CompilationFailedException ex) {
                    Logger.getLogger(Map.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Map.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jDialog2.setBounds(0, 0, 290, 390);
        jTextField3.setText(String.valueOf(constructing_map.popup_x));
        jTextField4.setText(String.valueOf(constructing_map.popup_y));
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jDialog3.setBounds(0, 0, 290, 390);
        jTextField9.setText(String.valueOf(constructing_map.popup_x));
        jTextField10.setText(String.valueOf(constructing_map.popup_y));
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(constructing_map!=null)
        {
            jDialog4.setBounds(0, 0, 190, 200);
            jDialog4.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(isInteger(jTextField11.getText()) && isInteger(jTextField12.getText()))
        {
            if(iseditting==false)
            {
                constructing_map.enemy_location[constructing_map.num_enemy]=new spawn_location_enemy(constructing_map,constructing_map.num_enemy,Integer.parseInt(jTextField11.getText()),Integer.parseInt(jTextField12.getText()),jComboBox3.getSelectedItem().toString());
                constructing_map.enemy_location[constructing_map.num_enemy].setVisible(true);
                constructing_map.add(constructing_map.enemy_location[constructing_map.num_enemy]);
                constructing_map.num_enemy=constructing_map.num_enemy+1;
                constructing_map.repaint();
                jDialog4.dispose();
            }else{
                
                constructing_map.enemy_location[editting_order].my_x_location=Integer.parseInt(jTextField11.getText());
                constructing_map.enemy_location[editting_order].my_y_location=Integer.parseInt(jTextField12.getText());
                constructing_map.enemy_location[editting_order].setBounds(Integer.parseInt(jTextField11.getText()),constructing_map.my_height-Integer.parseInt(jTextField12.getText())-constructing_map.enemy_location[editting_order].my_height,constructing_map.enemy_location[editting_order].my_width,constructing_map.enemy_location[editting_order].my_height);
                constructing_map.repaint();
                jDialog4.dispose();
                iseditting=false;
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jDialog4.setBounds(0, 0, 190, 200);
        jTextField11.setText(String.valueOf(constructing_map.popup_x));
        jTextField12.setText(String.valueOf(constructing_map.popup_y));
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void write_data(String file_path,String file_name,String exts) throws IOException{
                   System.out.println(file_path+exts);
                   //System.out.println(Paths.get(file_path+exts).toString());
                   File file = new File(file_path+"."+exts);
                   // creates the file
                   file.createNewFile();
                   // creates a FileWriter Object
                   FileWriter writer = new FileWriter(file); 
                   // Writes the content to the file
                   writer.write(Generated_file.getText()); 
                   writer.flush();
                   writer.close();
    }
    JTextArea Generated_file=new JTextArea();
    public void prepare_data()
    {
        Generated_file.append("import java.awt.Point;\n");
        Generated_file.append("import mygame.Floor;\n");
        Generated_file.append("import mygame.Map_constructor;\n");
        Generated_file.append("import mygame.constructing_floor;\n");
        Generated_file.append("import mygame.spawn_location;\n");
        Generated_file.append("import mygame.spawn_location_enemy;\n");
        Generated_file.append("import mygame.enemy_monster;\n");
        Generated_file.append("import java.awt.Dimension;\n");
        
        Generated_file.append("if(Main_menu.load_for_play==true){\n");
        Generated_file.append("Main_menu.app.running_map.maximum_width[0]="+constructing_map.my_width+";\n");
        Generated_file.append("Main_menu.app.running_map.maximum_height[0]="+constructing_map.my_height+";\n");
        Generated_file.append("Main_menu.app.running_map.map_array=new byte["+constructing_map.my_width+"]["+constructing_map.my_height+"][2];\n");
        Generated_file.append("Main_menu.app.running_map.my_background_tex[0]=\"Backgrounds/"+constructing_map.my_background_tex+"\";\n");
        Generated_file.append("Main_menu.app.running_map.mario_location[0]=new Point("+constructing_map.mario_location.my_x_location+","+constructing_map.mario_location.my_y_location+");\n");
        for(int i=0;i<constructing_map.num_floor;i++)
        {
            Generated_file.append("Main_menu.app.running_map.floor["+i+"]=new Floor(Main_menu.app.running_map,new Point("+constructing_map.floors[i].my_start_x+","+constructing_map.floors[i].my_start_y+"),"+constructing_map.floors[i].my_width+","+constructing_map.floors[i].my_height+",\""+constructing_map.floors[i].my_texture+"\","+constructing_map.floors[i].my_tile_x+","+constructing_map.floors[i].my_tile_y+");\n");
        }
        int num_monster=0;
        for(int i=0;i<constructing_map.num_enemy;i++)
        {
            if(constructing_map.enemy_location[i].my_name=="Monster")
            {
                Generated_file.append("Main_menu.app.running_map.all_enemy_monster["+i+"]=new enemy_monster(Main_menu.app,Main_menu.app.running_map,\"Characters/monster-left.png\",\"Characters/monster-right.png\","+constructing_map.enemy_location[i].my_x_location+","+constructing_map.enemy_location[i].my_y_location+","+num_monster+");");
                num_monster=num_monster+1;
            }
        }
        Generated_file.append("}else{\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map=new Map_constructor(Main_menu.current_map_making,"+constructing_map.my_width+","+constructing_map.my_height+",\""+constructing_map.my_background_tex+"\");\n");
        Generated_file.append("Main_menu.current_map_making.jPanel1.add(Main_menu.current_map_making.constructing_map);\n");
        Generated_file.append("Main_menu.current_map_making.jPanel1.setPreferredSize(new Dimension("+constructing_map.my_width+","+constructing_map.my_height+"));\n");
        Generated_file.append("Main_menu.current_map_making.repaint();\n");
        Generated_file.append("Main_menu.current_map_making.revalidate();\n");
        for(int i=0;i<constructing_map.num_floor;i++)
        {
            Generated_file.append("Main_menu.current_map_making.constructing_map.floors["+i+"]=new constructing_floor(Main_menu.current_map_making.constructing_map,"+constructing_map.floors[i].my_order+","+constructing_map.floors[i].my_start_x+","+constructing_map.floors[i].my_start_y+","+constructing_map.floors[i].my_width+","+constructing_map.floors[i].my_height+",\""+constructing_map.floors[i].my_texture+"\","+constructing_map.floors[i].my_tile_x+","+constructing_map.floors[i].my_tile_y+");\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.floors["+i+"].setVisible(true);\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.add(Main_menu.current_map_making.constructing_map.floors["+i+"]);\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.repaint();\n");
        }
        for(int i=0;i<constructing_map.num_enemy;i++)
        {
            Generated_file.append("Main_menu.current_map_making.constructing_map.enemy_location["+i+"]=new spawn_location_enemy(Main_menu.current_map_making.constructing_map,"+constructing_map.enemy_location[i].my_order+","+constructing_map.enemy_location[i].my_x_location+","+constructing_map.enemy_location[i].my_y_location+",\""+constructing_map.enemy_location[i].my_name+"\");\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.enemy_location["+i+"].setVisible(true);\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.add(Main_menu.current_map_making.constructing_map.enemy_location["+i+"]);\n");
            Generated_file.append("Main_menu.current_map_making.constructing_map.repaint();\n");
        }
        Generated_file.append("Main_menu.current_map_making.constructing_map.num_floor="+constructing_map.num_floor+";\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map.num_enemy="+constructing_map.num_enemy+";\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map.mario_location=new spawn_location(Main_menu.current_map_making.constructing_map,"+constructing_map.mario_location.my_x_location+","+constructing_map.mario_location.my_y_location+",\"Mario\");\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map.mario_location.setVisible(true);\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map.add(Main_menu.current_map_making.constructing_map.mario_location);\n");
        Generated_file.append("Main_menu.current_map_making.constructing_map.repaint();\n");
        Generated_file.append("}\n");
    }
    
    
public static boolean isInteger(String s) {
    try { 
        Integer.parseInt(s); 
    } catch(NumberFormatException e) { 
        return false; 
    }
    // only got here if we didn't return false
    return true;
}
public static boolean isFloat(String s) {
    try { 
        Float.parseFloat(s); 
    } catch(NumberFormatException e) { 
        return false; 
    }
    // only got here if we didn't return false
    return true;
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit_button;
    private javax.swing.JMenuItem Save_button;
    private javax.swing.JMenuItem Test_button;
    private javax.swing.JMenuItem add_floor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JDialog jDialog3;
    public javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    private javax.swing.JMenuItem mario_spawn;
    private javax.swing.JMenuItem new_map_button;
    // End of variables declaration//GEN-END:variables
}
